# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_subject_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='day',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='diary.DayOfWeek', verbose_name='день недели'),
            preserve_default=False,
        ),
    ]
