# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Описание сайта',
                'verbose_name_plural': 'Описание сайта',
            },
        ),
    ]
