# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20180827_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpost',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='автор'),
            preserve_default=False,
        ),
    ]
