# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpost',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
