# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_aboutpost_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPost',
        ),
    ]
