# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpost',
            name='slug',
            field=models.SlugField(default='about', max_length=10),
            preserve_default=False,
        ),
    ]
