# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpost',
            name='slug',
        ),
    ]
